server:
  port: 9527

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心创建路由的功能
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #动态路由service微服务地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            - After=2020-12-03T10:53:48.556+08:00[Asia/Shanghai] # 使用时区地址现在时间,或将来某一时间来控制访问, 一小时后可以访问如果没到时间访问返回404
            #- Before=2020-03-08T10:59:34.102+08:00[Asia/Shanghai] # 之前
            #- Between=2020-03-08T10:59:34.102+08:00[Asia/Shanghai] ,  2020-03-08T10:59:34.102+08:00[Asia/Shanghai] #之间
            #2020-03-08T10:59:34.102+08:00[Asia/Shanghai] must be before 2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            - Cookie=username,zzyy #必须携带cookie:curl http://localhost:9527/payment/lb --cookie "username=zzyy"
            - Header=X-Request-Id, \d+ #请求头要有x-request-id属性并且值为整数的正则表达式

        - id: baidu_routh1
          uri: http://news.baidu.com/guoji
          predicates:
            - Path=/guoji/**